In [1]:
from collections import defaultdict

# Sample corpus
corpus = [
    "He is Walter",
    "He is William",
    "He isn’t Peter or September"
]

# Function to tokenize sentences
def tokenize(sentence):
    return sentence.split()

# Function to calculate term frequency
def compute_tf(corpus):
    tf = []
    for document in corpus:
        tokens = tokenize(document)
        tf_doc = defaultdict(float)
        total_terms = len(tokens)
        for token in tokens:
            tf_doc[token] += 1.0 / total_terms
        tf.append(tf_doc)
    return tf

# Calculate term frequency
tf = compute_tf(corpus)

# Print term frequency for each document
for i, tf_doc in enumerate(tf):
    print(f"Term Frequency for document {i + 1}:")
    for term, freq in tf_doc.items():
        print(f"  {term}: {freq:.3f}")


Term Frequency for document 1:
  He: 0.333
  is: 0.333
  Walter: 0.333
Term Frequency for document 2:
  He: 0.333
  is: 0.333
  William: 0.333
Term Frequency for document 3:
  He: 0.200
  isn’t: 0.200
  Peter: 0.200
  or: 0.200
  September: 0.200


In [2]:
from sklearn.feature_extraction.text import CountVectorizer

# Sample corpus
corpus = [
    "this is a small example",
    "word embeddings are very useful",
    "we can use tensorflow to create embeddings"
]

# Initialize the CountVectorizer with term frequency
vectorizer = CountVectorizer()

# Fit and transform the corpus to term frequency vectors
X = vectorizer.fit_transform(corpus)

# Convert the term frequency matrix to an array
tf_array = X.toarray()

# Get the feature names (vocabulary)
feature_names = vectorizer.get_feature_names_out()

print("Vocabulary:", feature_names)
print("Term Frequency Matrix:\n", tf_array)


Vocabulary: ['are' 'can' 'create' 'embeddings' 'example' 'is' 'small' 'tensorflow'
 'this' 'to' 'use' 'useful' 'very' 'we' 'word']
Term Frequency Matrix:
 [[0 0 0 0 1 1 1 0 1 0 0 0 0 0 0]
 [1 0 0 1 0 0 0 0 0 0 0 1 1 0 1]
 [0 1 1 1 0 0 0 1 0 1 1 0 0 1 0]]
